version: "2"
services:
  mediawiki:
    image: mediawiki
    command: supervisord -c /etc/supervisor/supervisord.conf
    environment:
    - PORT=8002
    - WG_SITENAME=My KB
    - WG_META_NAMESPACE=My_KB
    - WG_PROTOCOL=http
    - WG_SERVER=localhost
    - WG_EMERGENCY_CONTACT=username@domain.com
    - WG_PASSWORD_SENDER=username@domain.com
    - WG_DB_SERVER=127.0.0.1
    - WG_DB_NAME=knowledge_base
    - WG_DB_USER=root
    - WG_DB_PASSWORD=cusdeb
    - ALLOW_ACCOUNT_CREATION=true
    - ALLOW_ACCOUNT_EDITING=true
    - ALLOW_ANONYMOUS_READING=true
    - ALLOW_ANONYMOUS_EDITING=true
    # Parsoid server
    # - PARSOID_HOST=127.0.0.1
    # - PARSOID_PORT=8003
    # - PARSOID_PROTOCOL=http
    network_mode: "host"
    volumes:
    - /srv/mediawiki/deleted:/var/www/w/deleted
    - /srv/mediawiki/images:/var/www/w/images

